# or configure ingress controller
apiVersion: v1
kind: Service
metadata:
  name: smg
spec:
  type: NodePort
  selector:
    app: smg
  ports:
    - name: "http"
      protocol: "TCP"
      port: 9000
      targetPort: 9000
      nodePort: 30077
