
- $rrd_socket: /var/rrdtool/rrdcached/rrdcached.sock
## set $rrdcached_update_batch_size to more than 1 to enable batched updates via socat and rrdcached protocol
## the following properties set the external socat command to use and whether to flush writes at the end of
## every run or before every read. Check the docs for more details
- $rrdcached_update_batch_size: 1000
#- $rrdcached_socat_command: "socat"
#- $rrdcached_flush_all_on_run: false
#- $rrdcached_flush_on_read: true

