
- $cdash:
  id: noc
  title: NOC
  items:
    - id: alerts
      title: Active alerts
      type: MonitorProblems
      width: 350
      height: 600
    - id: alert-log
      title: Alert Log
      type: MonitorLog
      width: 350
      height: 600
      limit: 50
      ms: WARNING
    - id: jmx.premote-graphs
      type: IndexGraphs
      title: jmx.premote Graphs
      width: 700
      height: 600
      ix: jmx.premote
      limit: 2
    - id: group1
      type: Container
      width: 700
      height: 800
      items:
      - id: index.states
        title: Index States
        type: IndexStates
        width: 450
        height: 500
        img_width: 300
        ixes:
          - jmx.premote
          - localhost
      - id: calc-netext
        type: Plugin
        width: 700
        height: 300
        plugin_id: calc
        ix: netext
    - id: localhost-9000
      title: External web page
      type: External
      width: 800
      height: 600
      url: http://localhost:9000/
