- ^localhost:
  title: "localhost graphs"
  px: "localhost."
#  cols: 2
#  rows: 1
  parent: hosts
#  agg_op: SUM
#  rows: 50
#  sx: ""
#  rx: ""

- $pre_fetch:
  id: host_localhost_up
  command: "ping -c 1 localhost >/dev/null"
  ignorets: true
  child_conc: 2
  notify-unkn: mail-asen

- $pre_fetch:
  id: fail_randomly
  pre_fetch: host_localhost_up
  command: 'bash -c "exit $(($RANDOM%2))"'
#  command: 'echo 0'

- +localhost.agg:
  op: SUM
  ids:
    - localhost.sysload
    - localhost.sysload2

- localhost.sysload:
  pre_fetch: host_localhost_up
  command: "smgscripts/mac_localhost_sysload.sh"
  interval: 60
  rrd_type: GAUGE
  vars:
    - label: 1min
#      alert-spike: ""
      #"1.5:15m:2h:0"
    - label: 5min
    - label: 15min

- localhost.sysload.stacked:
  pre_fetch: host_localhost_up
  command: "smgscripts/mac_localhost_sysload.sh"
  interval: 60
  rrd_type: GAUGE
  stack: true
  vars:
    - label: sl1min
#      alert-spike: ""
      #"1.5:15m:2h:0"
    - label: sl5min
    - label: sl15min

- localhost.sysload.stacked2:
  pre_fetch: host_localhost_up
  command: "smgscripts/mac_localhost_sysload.sh"
  interval: 60
  rrd_type: GAUGE
  stack: true
  vars:
    - label: sl1min
#      alert-spike: ""
      #"1.5:15m:2h:0"
    - label: sl5min
    - label: sl15min

- localhost.sysload2:
  pre_fetch: fail_randomly
  command: "smgscripts/mac_localhost_sysload.sh"
  interval: 60
  rrd_type: GAUGE
  vars:
    - label: 1min_x100
      cdef: "$ds,100,*"
    - label: 5min_x100
      cdef: "$ds,100,*"
    - label: 15min_x100
      cdef: "$ds,100,*"

- localhost.dummy:
  title: "A dummy graph for this host"
  command: "echo 2 && echo 1"
#  options:
  pre_fetch: host_localhost_up
  interval: 60
  rrd_type: GAUGE
  vars:
    - label: val1
    - label: val2

- localhost.dummy3:
  pre_fetch: fail_randomly
  command: "smgscripts/echo4.sh"
  title: "A dummy graph with 3 vals"
#  options:
  interval: 60
#  rrd_type: COUNTER
  vars:
    - label: val31
      min: 0
      max: 10
      alert-warn-gt: 3
      alert-crit-gt: 8
    - label: val32
    - label: val33

- localhost.dummy3-21:
  title:  "A dummy graph with 3 vals and 2 selected"
  ref: localhost.dummy3
#  gv:
#   - 2
#   - 1
  cdef_vars:
    - label: sumv1v2
      cdef: "$ds1,$ds2,+"


- localhost.dummy1:
  title: "A dummy graph for this host 1"
  pre_fetch: fail_randomly
  command: "echo 2 && echo 1"
#  options:
  interval: 60
  rrd_type: GAUGE
  vars:
    - label: val1
      alert-p-mon-pop: "24h:lt:0.5:0.7"

- localhost.time.counter:
  title: "Test time counter"
  command: "date +%s"
#  options:
  interval: 60
  rrd_type: COUNTER
  vars:
    - label: sec/sec
      max: 1.01

- localhost.time.counter2:
  title: "Test time counter2"
  command: "date +%s"
#  options:
  interval: 60
  rrd_type: COUNTER
  vars:
    - label: sec/sec
      max: 1.01

- +localhost.time.counter.agg:
  title: localhost time counter agg
  op: SUM
  ids:
    - localhost.time.counter
    - localhost.time.counter2
  vars:
    - label: sum sec/sec

- localhost.spike.check:
  title: "Test spike"
  command: "smgscripts/print-series.rb smgscripts/print-series-test.txt"
#  options:
  interval: 60
  rrd_type: GAUGE
  rrd_init_source: localhost.spike.check.rrd.old
  vars:
    - label: num
      alert-p-mon-anom: "1.5:15m:2h:0"
      alert-p-mon-pop: "24h:lt:0.7:0.5"


- localhost.ex1.cdef:
  title: "A cdef graph for this host 1"
  command: "echo 1 && echo 2"
#  options:
  interval: 60
  rrd_type: GAUGE
  vars:
    - label: val1
      cdef: "$ds,10,*"
    - label: val2
      cdef: "$ds,10,*"

- localhost.ex1.cdefv:
  title: "A cdef var graph for this host 1"
  ref: localhost.ex1.cdef
  cdef_vars:
    - label: val1-cdf
      cdef: "$ds1,$ds0,/"

- localhost.ex2.cdef:
  title: "A cdef graph for this host 2"
  command: "echo 3 && echo 4"
#  options:
  interval: 60
  rrd_type: GAUGE
  vars:
    - label: val1
      cdef: "$ds,10,*"
    - label: val2
      cdef: "$ds,10,*"

- localhost.ex2.cdefv:
  title: "A cdef var graph for this host 1"
  ref: localhost.ex2.cdef
  cdef_vars:
    - label: val1-cdf
      cdef: "$ds1,$ds0,/"

- ^jmx.xremote:
  rx: .jmx.smg
  remote: "*"
  agg_op: GROUP
  xagg: true

- ^jmx.premote:
  rx: .jmx.smg
  remote: "*"
  agg_op: GROUP
