## This is an example SMG configuration file.
## Note: all paths below are relative to the SMG install dir (use absolute paths to be sure)

## The commented out global values are all optional and show their default values

## Graph properties
#- $rrd_graph_width: 607
#- $rrd_graph_height: 152
#- $rrd_graph_font: "DEFAULT:0:monospace"

## rrdtool executable
#- $rrd_tool: rrdtool

## path to rrdcached socket, if used.
#- $rrd_socket: /path/to/socket.fn

## set $rrdcached_update_batch_size to more than 1 to enable batched updates via socat and rrdcached protocol
## the following properties set the external socat command to use and whether to flush writes at the end of
## every run or before every read. Check teh docs for more details
#- $rrdcached_update_batch_size: 1
#- $rrdcached_socat_command: "socat"
#- $rrdcached_flush_all_on_run: false
#- $rrdcached_flush_on_read: true


## Don't change img_dir unless you setup a http reverse proxy + web server to serve them
#- $img_dir: "public/smg"

## Directory where to store rrd files. Recommended to point outside SMG dir and do regular backups.
#- $rrd_dir: "smgrrd"

## Monitor logs outpt dir. May want to point outside SMG install dir if one cares about these and upgrades
#- $monlog_dir: "monlog"

## Monitor state outout dir. May want to point outside SMG install dir if one cares about these and upgrades
#- $monstate_dir: "monstate"

## Directory where to store cached remote rrd files. Leave alone if uncertain.
#- $rrd_cache_dir: "smgrrd"

## Include the default linux localhost sytem stats template
- $include: "smgconf/templ-linux-pf.yml"
## Replace the above with this on Mac
#- $include: "smgconf/templ-mac-localhost.yml"

## Other includes as needed
#- $include: "smgconf/templ-linux-naive.yml"
#- $include: "smgconf/config-alerts.yml"
- $include: "smgconf/localhost-jmx.yml"

# drop-in dir to add more confs - create a yml there and run smgscripts/reload-conf.sh.
- $include: "/etc/smg/cust/*.yml"
